name: mood_vibe
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.0.8
  google_generative_ai: ^0.4.7
  url_launcher: ^6.2.5
  
  # 📍 เปิดใช้งานเครื่องเล่นเพลงอย่างภาคภูมิใจ
  just_audio: ^0.10.5
  http: ^1.6.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/avatars/