// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgt6_yFVy1xSMrcY4bzLKWDOWGWwLsu-A',
    appId: '1:389288165312:web:0a06175104e6004ecf9225',
    messagingSenderId: '389288165312',
    projectId: 'moodvibe-f59af',
    authDomain: 'moodvibe-f59af.firebaseapp.com',
    storageBucket: 'moodvibe-f59af.firebasestorage.app',
    measurementId: 'G-75CBXBSJ7E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMjpJexp_rUn8fzqmwyIC2AjhL7uElhAU',
    appId: '1:389288165312:android:41a01db28bc26e51cf9225',
    messagingSenderId: '389288165312',
    projectId: 'moodvibe-f59af',
    storageBucket: 'moodvibe-f59af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4E7ya6ep0jhkxGaEUp73koBrqod65Dco',
    appId: '1:389288165312:ios:1c5c23e6d502e7efcf9225',
    messagingSenderId: '389288165312',
    projectId: 'moodvibe-f59af',
    storageBucket: 'moodvibe-f59af.firebasestorage.app',
    iosBundleId: 'com.example.moodVibe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4E7ya6ep0jhkxGaEUp73koBrqod65Dco',
    appId: '1:389288165312:ios:1c5c23e6d502e7efcf9225',
    messagingSenderId: '389288165312',
    projectId: 'moodvibe-f59af',
    storageBucket: 'moodvibe-f59af.firebasestorage.app',
    iosBundleId: 'com.example.moodVibe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgt6_yFVy1xSMrcY4bzLKWDOWGWwLsu-A',
    appId: '1:389288165312:web:d8411df93e883a7fcf9225',
    messagingSenderId: '389288165312',
    projectId: 'moodvibe-f59af',
    authDomain: 'moodvibe-f59af.firebaseapp.com',
    storageBucket: 'moodvibe-f59af.firebasestorage.app',
    measurementId: 'G-ZRPDLLQ401',
  );
}
